### ISSUE TITLE
Invalid CFBundleSupportedPlatforms value iPhoneSimulator in FFmpeg.framework

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/DJIWidget#30]
I cannot upload an updated version of my app which contains the DJI-SDK, DJIWidget(which contains FFMpeg) to Testflight after updating to Xcode 13. When I try I get:

`Invalid CFBundleSupportedPlatforms value. The CFBundleSupportedPlatforms key in the Info.plist file in “Payload/app.app/Frameworks/FFmpeg.framework” bundle contains an invalid value, [iPhoneSimulator]. Consider removing the CFBundleSupportedPlatforms key from the Info.plist file. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue. With error code STATE_ERROR.VALIDATION_ERROR.90542 for id f2327257-ad48-4b60-8fc8-a518da5fbac8
`

```
# relevant pods
pod 'DJI-SDK-iOS', '~> 4.16'
pod 'DJIWidget', '~> 1.6.6'
```
However FFMpeg seems to be a binary file Framework attached to DJIWidget so I can't edit the Info.plist directly. Is there any way to workaround this or is a change required in DJIWidget?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/62345'>Zendesk ticket #62345</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
Will report to the dev team.

**Comment by brien-crean** [comment]
The workaround [here](https://github.com/dji-sdk/Mobile-SDK-iOS/issues/510#issue-1190969561) works.

@dji-dev can you please ask the dev team to adjust the [Info.plist](https://github.com/dji-sdk/DJIWidget/blob/master/FFmpeg/FFmpeg.framework/Info.plist) file in a future DJIWidget version

**Comment by DJI-William** [comment]
We have change the [Info.plist](https://github.com/dji-sdk/DJIWidget/blob/master/FFmpeg/FFmpeg.framework/Info.plist) as you have mention here. After our internal testing, we will update to the Github.

**Comment by Yourney** [comment]
Until the DJI-fix is released, you can add a Run script to your target that removes the offending line:
plutil -remove "CFBundleSupportedPlatforms" Pods/DJIWidget/FFmpeg/FFmpeg.framework/info.plist
